<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>b6b0d253-ca6e-4f95-8da3-270cecdd8e01</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.9" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RealEstateAnalytics.Core\RealEstateAnalytics.Core.csproj" />
    <ProjectReference Include="..\RealEstateAnalytics.DataProvider\RealEstateAnalytics.DataProvider.csproj" />
  </ItemGroup>

</Project>
